import Layout from "../layout/Layout";
import Head from "next/head";
import "../styles/global.css";
import { CssBaseline } from "@mui/material";

export default function MyApp(props) {
  const { Component, pageProps } = props;
  return (
    <div>
      <Head>
        <title>KanBoard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="../public/favicon.ico" />
      </Head>
      <CssBaseline />
      <Layout>
        <Component {...pageProps} />
      </Layout>
    </div>
  );
}
